Relayout the feedback form for consistency
sul-dlss/purl pull request #498
Opened 2021-06-08 22:06 UTC by mjgiarlo

Fixes #421

This commit contains a number of changes related to tweaking the layout of the feedback form:

* Requested style changes (see screenshots)
* As part of moving to Bootstrap 5, manage jquery via webpacker which gives us more control over load order (JQuery must be loaded before Bootstrap or BS controls do not function---to wit, the collapsible div is currently broken in deployed environments such that it only collapses when submitted not when cancelled)
* Use recaptcha gem to support ReCAPTCHA use case for unauthenticated users
* Minor JavaScript formatting tweaks
* Remove code from feedback_forms.js that doesn't seem necessary anymore, including the link-to-button functionality
* Fix the styling of BS alerts generated from within javascript (currently, error flashes are unstyled)
* Embangify a private method in FeedbackFormsController (stylistic only)
* Load JQuery before Bootstrap in webpacker config

# Screencast

![Peek 2021-06-08 14-33](https://user-images.githubusercontent.com/131982/121263819-1556d480-c86b-11eb-849e-5eedf19031ab.gif)

# Screenshots

## BEFORE

![before](https://user-images.githubusercontent.com/131982/121263849-1ab41f00-c86b-11eb-83c0-467f4e13ca61.png)

## AFTER

![after](https://user-images.githubusercontent.com/131982/121263857-1d167900-c86b-11eb-9aee-fc74b94c9c44.png)

2021-06-08 22:08 UTC, mjgiarlo commented
Have a look, @ggeisler ?

2021-06-08 23:42 UTC, ggeisler requested changes
I have one suggestion (though I think it might apply to multiple contexts): 

- The alert message dismissal icon should be right-aligned in the alert box, rather than following immediately after the message text as it appears in the screenshots

See https://getbootstrap.com/docs/5.0/components/alerts/#dismissing for an example if what I'm talking about isn't clear.

Other than that, looks good to me from the UI point of view @mjgiarlo.

2021-06-09 00:13 UTC, mjgiarlo commented
@ggeisler :speech_balloon: 
> I have one suggestion (though I think it might apply to multiple contexts):
> 
> * The alert message dismissal icon should be right-aligned in the alert box, rather than following immediately after the message text as it appears in the screenshots

Good catch! I missed the `alert-dismissible` class. Here we go:

![Screenshot from 2021-06-08 17-10-17](https://user-images.githubusercontent.com/131982/121273263-b69a5680-c87c-11eb-899c-9dc4759581fe.png)

2021-06-09 00:18 UTC, ggeisler approved these changes
👍

2021-06-09 01:03 UTC, cbeer approved these changes

2021-06-09 23:25 UTC, camillevilla approved these changes
Looks great @mjgiarlo! Thanks for the BS5 notes.

2021-06-09 23:28 UTC, merged