Adds items in this collection section.
sul-dlss/purl pull request #724
Opened 2023-10-23 19:03 UTC by justinlittman

closes #714

![image](https://github.com/sul-dlss/purl/assets/588335/86678118-25da-44c5-bfe6-05c667ff7c0e)

2023-10-24 02:20 UTC, jcoyne commented on app/models/public_xml.rb
> +    document.root.at_xpath('identityMetadata/objectType').try(:text)
Why try here? There shouldn't be any nodes with out an objectType, right? That's pretty fundamental.

2023-10-24 02:37 UTC, jcoyne requested changes

2023-10-24 02:37 UTC, jcoyne commented on app/views/purl/_collection_items.html.erb
> +<% if @purl.object_type == 'collection' && @purl.catalog_key %>
Can you make a method `collection?` here?

2023-10-24 02:37 UTC, jcoyne commented on app/views/purl/_collection_items.html.erb
> +  <%= link_to 'View items in this collection in SearchWorks', "#{Settings.searchworks.url}/catalog?f[collection][]=#{@purl.catalog_key}" %>
Is it possible the collection is not released to searchworks?

2023-10-24 02:37 UTC, jcoyne commented on spec/views/purl/_collection_items.html.erb_spec.rb
> +    it 'displays a View items in this collection link' do
Isn't this same scenario tested in the integration test?

2023-10-24 02:37 UTC, jcoyne commented on spec/views/purl/_collection_items.html.erb_spec.rb
> +      expect(rendered).not_to have_css 'a', text: 'View items in this collection in SearchWorks'
These two negative assertion tests are very fragile because a change to the text in the template that does not also change these tests completely makes these assertions useless. E.g we could show a link, but since the text has changed we won't catch it.

2023-10-24 02:37 UTC, jcoyne commented on app/views/purl/_mods_metadata_sections.html.erb
> +<% if collection_items.present? %>
Can't you just move all of this into the partial?  That is already wrapped in a conditional.  Alternatively if you introduce a ViewComponent here, you can make this be the `render?` condition.  I find that much easier to read and test rather than this approach here.

2023-10-24 02:37 UTC, jcoyne commented on spec/model/purl_resource_spec.rb
> +      allow(subject).to receive(:public_xml_body).and_return <<-EOF
Please move this to a `before` as it's part of setting up the scenario and has no assertions.

2023-10-24 03:01 UTC, jcoyne commented on app/views/purl/_collection_items.html.erb
> +  <%= link_to 'View items in this collection in SearchWorks', "#{Settings.searchworks.url}/catalog?f[collection][]=#{@purl.catalog_key}" %>
Nope, because it has a catalog key.

2023-10-24 03:04 UTC, jcoyne commented on spec/views/purl/_collection_items.html.erb_spec.rb
> +  context 'when an unpublished collection' do
How do we know it's "unpublished"?  Do you mean "doesn't have a catkey"?  I'm concerned that we're overloading what "published" means.

2023-10-24 11:26 UTC, justinlittman commented on app/models/public_xml.rb
> +    document.root.at_xpath('identityMetadata/objectType').try(:text)
Because every other call to `.text` in this class is `.try(:text)`. I have no idea why that would be, but following existing conventions.

2023-10-24 11:33 UTC, justinlittman commented on app/views/purl/_collection_items.html.erb
> +<% if @purl.object_type == 'collection' && @purl.catalog_key %>
I would have, except `PurlResource` already has a `.collection` method which provides the collection that the item is a part of. It seems that a `.collection?` method that indicates whether this item is a collection risks confusion.

2023-10-24 11:35 UTC, justinlittman commented on spec/views/purl/_collection_items.html.erb_spec.rb
> +    it 'displays a View items in this collection link' do
Yes, but I wanted the test cases in this spec to be complete so that a dev could understand the expected behavior from the view from this alone.

The integration test is necessary because it tests that the view is actually called.

2023-10-24 11:42 UTC, justinlittman commented on spec/views/purl/_collection_items.html.erb_spec.rb
> +      expect(rendered).not_to have_css 'a', text: 'View items in this collection in SearchWorks'
I couldn't figure out how to assert nothing is rendered, so just removed the text assertion.

2023-10-24 11:44 UTC, justinlittman commented on app/views/purl/_mods_metadata_sections.html.erb
> +<% if collection_items.present? %>
I agree with you, but I am following the existing pattern in this file. I'm not trying to refactor in this PR.

2023-10-24 11:44 UTC, justinlittman commented on spec/model/purl_resource_spec.rb
> +      allow(subject).to receive(:public_xml_body).and_return <<-EOF
I'm just following the pattern in this file.

2023-10-24 11:46 UTC, justinlittman commented on spec/views/purl/_collection_items.html.erb_spec.rb
> +  context 'when an unpublished collection' do
OK, changed to `when collection does not have a catalog record id`.

2023-10-24 12:18 UTC, jcoyne commented on app/views/purl/_collection_items.html.erb
> +<% if @purl.object_type == 'collection' && @purl.catalog_key %>
I still feel that we should move as much logic from the views as possible.  If we need to rename `collection` to `is_member_of`, I think that would be good to and help align with Cocina terminology.

2023-10-24 12:19 UTC, jcoyne commented on app/models/public_xml.rb
> +    document.root.at_xpath('identityMetadata/objectType').try(:text)
I don't think that's a very good reason. A lot of this code was written 12 years ago before the model was clear and before there was a safe navigation operator in Ruby.

2023-10-24 12:21 UTC, jcoyne commented on spec/model/purl_resource_spec.rb
> +      allow(subject).to receive(:public_xml_body).and_return <<-EOF
This codebase is full of bad patterns and needs to be over hauled. Please use practices like https://www.betterspecs.org/#mock and not the existing patterns here.

2023-10-24 18:47 UTC, jcoyne commented on app/views/purl/_collection_items.html.erb
> +<% if @purl.object_type == 'collection' && @purl.catalog_key %>
This method name has been refactored, so please move this to the `collection?` method now.

2023-10-24 18:47 UTC, jcoyne commented on app/views/purl/_mods_metadata_sections.html.erb
> +<% if collection_items.present? %>
I've changed the existing pattern in https://github.com/sul-dlss/purl/pull/727 so please follow that pattern here.

2023-10-24 18:49 UTC, jcoyne commented
There are now conflicts with the DOI feature.

2023-10-25 13:47 UTC, justinlittman commented
Superceded by #736

2023-10-25 13:47 UTC, closed without merging