Set up analytics tracking with ahoy
sul-dlss/purl pull request #743
Opened 2023-10-26 22:25 UTC by thatbudakguy

- Set up Ahoy for analytics tracking
- Set up a SQLite database for tracking analytics
- Add view and download tracking accessors to PurlResource

2023-10-27 03:01 UTC, jcoyne requested changes

2023-10-27 03:01 UTC, jcoyne commented on spec/rails_helper.rb
>    config.use_transactional_fixtures = false
Can't you just set this to `true` and then you don't need `DatabaseCleaner`?

2023-10-27 03:02 UTC, jcoyne requested changes

2023-10-27 03:02 UTC, jcoyne commented on config/database.yml
> +  <<: *default
Purl prod is load balanced, so you aren't going to be able to use a sqlite database, right?

2023-10-27 03:54 UTC, jcoyne commented on config/database.yml
> +  <<: *default
I see #744

2023-10-27 18:10 UTC, thatbudakguy commented on config/database.yml
> +  <<: *default
Yeah, this defers the solution for prod for the time being.

2023-10-27 18:10 UTC, thatbudakguy commented on spec/rails_helper.rb
>    config.use_transactional_fixtures = false
I tried that and it didn't actually clean the database. 🤷🏻 I copied this config from another app where we used this setup, and it did what I wanted.

2023-11-01 13:12 UTC, jcoyne commented on spec/rails_helper.rb
>    config.use_transactional_fixtures = false
There is almost no reason for it in a modern Rails app.  Please don't stuff this in this PR.

2023-11-03 17:56 UTC, thatbudakguy commented
superseded by https://github.com/sul-dlss/metrics/pull/6

2023-11-03 17:56 UTC, closed without merging