Adds navPlace to iiif manifest.
sul-dlss/purl pull request #752
Opened 2023-10-31 16:51 UTC by justinlittman

closes #708

A point:
![image](https://github.com/sul-dlss/purl/assets/588335/6c38a56f-6ccc-4f56-a19d-8132c23e3861)

A polygon:
![image](https://github.com/sul-dlss/purl/assets/588335/3d3d786b-8b6b-4abf-83be-33cb218df25f)

2023-10-31 17:28 UTC, jcoyne requested changes

2023-10-31 17:28 UTC, jcoyne commented on app/models/iiif3_presentation_manifest.rb
> +  class NavPlace
Can you decouple this class from `public_xml_document`? Then would you please move this into https://github.com/iiif-prezi/osullivan ?  That is where we keep all the manifest building tools.

2023-11-08 22:35 UTC, thatbudakguy commented
after some hands-on testing today, I'm going to merge this, noting that #761 should be the next step.

2023-11-08 22:35 UTC, thatbudakguy approved these changes

2023-11-08 22:35 UTC, merged