Upgrade to Rails 7.1.
sul-dlss/purl pull request #779
Opened 2023-11-03 20:26 UTC by justinlittman

closes #769

2023-11-03 20:43 UTC, cbeer commented
Did you run `rails app:update`? I'm surprised there aren't the environment + config updates that usually come with a Rails bump.

2023-11-03 20:54 UTC, justinlittman commented
Duh. No.

2023-11-07 18:26 UTC, lwrubel commented
Just checking: is this ready for review now?

2023-11-07 18:44 UTC, jcoyne requested changes

2023-11-07 18:44 UTC, jcoyne commented on config/environments/development.rb
> +  config.active_job.verbose_enqueue_logs = true
We don't use active_job, so this should be commented out.

2023-11-07 18:44 UTC, justinlittman commented
Yes

2023-11-07 18:47 UTC, justinlittman commented on config/environments/development.rb
> +  config.active_job.verbose_enqueue_logs = true
Commented out.

2023-11-08 12:48 UTC, jcoyne approved these changes

2023-11-08 12:48 UTC, merged