New purl page layout.
sul-dlss/purl pull request #815
Opened 2023-11-10 19:08 UTC by justinlittman

closes #799

2023-11-16 21:35 UTC, jcoyne commented on Gemfile
> +gem 'mods_display', github: 'sul-dlss/mods_display', branch: 'design'
Can you test this change first/separately?  We need to ensure this is safe to push out to all environments without other changes (unless this is a major version).

2023-11-16 21:37 UTC, jcoyne commented on app/assets/stylesheets/modules/record-metadata-section.scss
> +    margin-bottom: 25px;
Can you use rems instead? See https://austingil.com/px-or-rem-in-css/

2023-11-16 21:38 UTC, jcoyne commented on app/assets/stylesheets/modules/record-metadata-section.scss
> +        font-size: 0px;
We don't need units for 0, right?

2023-11-16 21:39 UTC, jcoyne commented on app/assets/stylesheets/modules/record-metadata-section.scss
> +        font-size: 0px;
How about `th > * { visibility: hidden }`?

2023-11-16 21:44 UTC, jcoyne requested changes

2023-11-16 21:44 UTC, jcoyne commented on app/assets/stylesheets/sul-variables.scss
> +$sul-link-color: mediumblue;
Shouldn't this be one of the colors from the brand identity? https://identity.stanford.edu/design-elements/color/web/

2023-11-16 21:44 UTC, jcoyne commented on app/components/section_component.html.erb
> +    <%# Omitting for now until it is known what this icon is used for. %>
when will this happen?

2023-11-16 21:44 UTC, jcoyne commented on app/components/section_component.html.erb
> +<div class="section" <% if id%>id="<%= id %>"<% end %> <% if side_nav_class %>data-side-nav-class="<%= side_nav_class %>"<% end %>>
I think `<%= tags.div { class: 'section', id:, 'data-side-nav-class' => side_nav_class }.compact } do %>` is more readable here.

2023-11-17 20:39 UTC, justinlittman commented on Gemfile
> +gem 'mods_display', github: 'sul-dlss/mods_display', branch: 'design'
Yes, it will be possible to test this change first/separately. I refactored my changes to mods_display so they should not change rendering for existing applications.

2023-11-20 13:10 UTC, justinlittman commented on app/assets/stylesheets/sul-variables.scss
> +$sul-link-color: mediumblue;
Makes sense. Fixed.

2023-11-20 13:30 UTC, justinlittman commented on app/components/section_component.html.erb
> +<div class="section" <% if id%>id="<%= id %>"<% end %> <% if side_nav_class %>data-side-nav-class="<%= side_nav_class %>"<% end %>>
Fixed.

2023-11-20 13:38 UTC, justinlittman commented on app/assets/stylesheets/modules/record-metadata-section.scss
> +        font-size: 0px;
```
tr.middle-row th > *, tr.last-row th > * {
        // Visibility hidden doesn't work here because it also hides the border
        // font-size: 0px;
        visibility: hidden;
      }
```

![image](https://github.com/sul-dlss/purl/assets/588335/d93ec360-744e-4aed-8303-c0e3cb170580)

2023-11-30 20:49 UTC, jcoyne commented on app/assets/stylesheets/modules/record-metadata-section.scss
> +        }
Cruft?

2023-12-01 15:01 UTC, jcoyne commented on app/components/section_component.html.erb
> +  <div class="section-heading">
Is this div necessary?  Can we just move the class to the h2?

2023-12-01 15:02 UTC, jcoyne commented on app/components/section_component.html.erb
> +<div class="section">
Should this be a `<section>` tag?

2023-12-01 15:04 UTC, jcoyne reviewed
Consider pulling the SectionComponent out to it's own pull request. I think that would make the PRs easier to review as it reduces the size/complexity into more manageable chunks.

2023-12-01 19:29 UTC, justinlittman commented on app/assets/stylesheets/modules/record-metadata-section.scss
> +    margin-bottom: 25px;
Done.

2023-12-04 19:34 UTC, jcoyne commented on app/assets/stylesheets/modules/record-metadata-section.scss
> +        font-size: 0px;
What if they go in a span?

2023-12-04 19:35 UTC, jcoyne commented on app/components/mods_definition_list_component.rb
> +    { class: 'visually-hidden' }
Is this coupling to bootstrap 5?  How can we express that dependency?

2023-12-04 19:51 UTC, jcoyne approved these changes

2023-12-04 19:51 UTC, merged