[HOLD] Build the sitemap from the release tags
sul-dlss/purl pull request #973
Opened 2024-04-16 14:55 UTC by jcoyne

Fixes #971

2024-04-16 19:47 UTC, justinlittman requested changes

2024-04-16 19:47 UTC, justinlittman commented on app/models/purl_resource.rb
>    def crawlable?
Can you get rid of this method?

2024-04-16 19:49 UTC, jcoyne commented on app/models/purl_resource.rb
>    def crawlable?
It's called in `app/views/purl/show.html.erb`

2024-04-16 19:51 UTC, justinlittman commented on app/models/purl_resource.rb
>    def crawlable?
Ah, OK.

2024-04-16 19:52 UTC, justinlittman approved these changes

2024-04-19 18:35 UTC, justinlittman commented
This has been tested so merging.

2024-04-19 18:35 UTC, merged